2020-09-26 10:15:58 Hail: INFO: Running Hail version 0.2.57-582b2e31b8bd
2020-09-26 10:15:58 SparkContext: WARN: Using an existing SparkContext; some configuration may not take effect.
2020-09-26 10:15:59 root: ERROR: URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
From java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
	at org.apache.hadoop.fs.Path.initialize(Path.java:205)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.fileStatus(HadoopFS.scala:150)
	at is.hail.io.fs.FS$class.isFile(FS.scala:164)
	at is.hail.io.fs.HadoopFS.isFile(HadoopFS.scala:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.checkChar(URI.java:3030)
	at java.net.URI$Parser.parse(URI.java:3046)
	at java.net.URI.<init>(URI.java:746)
	at org.apache.hadoop.fs.Path.initialize(Path.java:202)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.fileStatus(HadoopFS.scala:150)
	at is.hail.io.fs.FS$class.isFile(FS.scala:164)
	at is.hail.io.fs.HadoopFS.isFile(HadoopFS.scala:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)




2020-09-26 10:16:09 root: ERROR: URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
From java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
	at org.apache.hadoop.fs.Path.initialize(Path.java:205)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:98)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:102)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_*.perc_0.5.tsv
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.checkChar(URI.java:3030)
	at java.net.URI$Parser.parse(URI.java:3046)
	at java.net.URI.<init>(URI.java:746)
	at org.apache.hadoop.fs.Path.initialize(Path.java:202)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:98)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:102)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)




2020-09-26 10:16:16 root: ERROR: URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_%5C*.perc_0.5.tsv
From java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_%5C*.perc_0.5.tsv
	at org.apache.hadoop.fs.Path.initialize(Path.java:205)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:98)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:102)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

java.net.URISyntaxException: Illegal character in scheme name at index 0:  gs://nbaya/sexdiff/prs/prs.4080_irnt.male.n_remove_10000.seed_73178.unadjusted.pruned.pval_thresh_%5C*.perc_0.5.tsv
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.checkChars(URI.java:3020)
	at java.net.URI$Parser.checkChar(URI.java:3030)
	at java.net.URI$Parser.parse(URI.java:3046)
	at java.net.URI.<init>(URI.java:746)
	at org.apache.hadoop.fs.Path.initialize(Path.java:202)
	at org.apache.hadoop.fs.Path.<init>(Path.java:171)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:98)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:102)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)




2020-09-26 10:16:30 root: ERROR: IOException: No FileSystem for scheme: gs
From java.io.IOException: No FileSystem for scheme: gs
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at is.hail.io.fs.HadoopFS.getFileSystem(HadoopFS.scala:98)
	at is.hail.io.fs.HadoopFS.listStatus(HadoopFS.scala:102)
	at is.hail.utils.Py4jUtils$class.ls(Py4jUtils.scala:55)
	at is.hail.utils.package$.ls(package.scala:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)



2020-09-26 10:23:34 SparkContext: INFO: Invoking stop() from shutdown hook
2020-09-26 10:23:34 AbstractConnector: INFO: Stopped Spark@bdd9821{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2020-09-26 10:23:34 SparkUI: INFO: Stopped Spark web UI at http://10.26.239.71:4040
2020-09-26 10:23:35 MapOutputTrackerMasterEndpoint: INFO: MapOutputTrackerMasterEndpoint stopped!
2020-09-26 10:23:35 MemoryStore: INFO: MemoryStore cleared
2020-09-26 10:23:35 BlockManager: INFO: BlockManager stopped
2020-09-26 10:23:35 BlockManagerMaster: INFO: BlockManagerMaster stopped
2020-09-26 10:23:35 OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: INFO: OutputCommitCoordinator stopped!
2020-09-26 10:23:35 SparkContext: INFO: Successfully stopped SparkContext
2020-09-26 10:23:35 ShutdownHookManager: INFO: Shutdown hook called
2020-09-26 10:23:35 ShutdownHookManager: INFO: Deleting directory /private/var/folders/v4/w7rkkv_x2_zcsszmps6x2dkm0000gn/T/spark-e5bc78ab-9469-41e0-b927-cc4926381069/pyspark-d02a2eda-91ae-4731-9b5a-15769ccf5ddf
2020-09-26 10:23:35 ShutdownHookManager: INFO: Deleting directory /private/var/folders/v4/w7rkkv_x2_zcsszmps6x2dkm0000gn/T/spark-1eb43b51-6042-4ce9-9009-6b72e8f7da22
2020-09-26 10:23:35 ShutdownHookManager: INFO: Deleting directory /private/var/folders/v4/w7rkkv_x2_zcsszmps6x2dkm0000gn/T/spark-e5bc78ab-9469-41e0-b927-cc4926381069
